// Datos locales de alumnos para pruebas
export const alumnosIniciales = [
  {
    id: "1",
    dni: "12345678",
    nombre: "Juan",
    apellido1: "Pérez",
    apellido2: "García",
    nivelEstudio: 2,
    grado: 3,
    sede: 1,
    gradoSeccion: "3ro Secundaria",
    sedeNombre: "Sede Carrión",
  },
  {
    id: "2",
    dni: "87654321",
    nombre: "María",
    apellido1: "González",
    apellido2: "López",
    nivelEstudio: 1,
    grado: 5,
    sede: 2,
    gradoSeccion: "5to Primaria",
    sedeNombre: "Sede Británico",
  },
  {
    id: "3",
    dni: "45678912",
    nombre: "Carlos",
    apellido1: "Rodríguez",
    apellido2: "Martínez",
    nivelEstudio: 2,
    grado: 4,
    sede: 1,
    gradoSeccion: "4to Secundaria",
    sedeNombre: "Sede Carrión",
  },
  {
    id: "4",
    dni: "78912345",
    nombre: "Ana",
    apellido1: "Sánchez",
    apellido2: "Fernández",
    nivelEstudio: 1,
    grado: 2,
    sede: 2,
    gradoSeccion: "2do Primaria",
    sedeNombre: "Sede Británico",
  },
  {
    id: "5",
    dni: "56789123",
    nombre: "Luis",
    apellido1: "Torres",
    apellido2: "Ramírez",
    nivelEstudio: 2,
    grado: 1,
    sede: 1,
    gradoSeccion: "1ro Secundaria",
    sedeNombre: "Sede Carrión",
  },
]
