// Datos locales de docentes para pruebas
export const docentesIniciales = [
  {
    id: "1",
    dni: "12345678",
    nombre: "Juan Carlos",
    apellido1: "Pérez",
    apellido2: "García",
    telefono: "987654321",
    email: "juan.perez@colegio.edu.pe",
    direccion: "Av. Los Maestros 123, Lima",
    // Campos adicionales para compatibilidad con el modal
    nombreDocente: "Juan Carlos",
    apellidoPaterno: "Pérez",
    apellidoMaterno: "García",
    correoElectronico: "juan.perez@colegio.edu.pe",
  },
  {
    id: "2",
    dni: "87654321",
    nombre: "María Elena",
    apellido1: "González",
    apellido2: "López",
    telefono: "976543210",
    email: "maria.gonzalez@colegio.edu.pe",
    direccion: "Jr. Educación 456, Lima",
    nombreDocente: "María Elena",
    apellidoPaterno: "González",
    apellidoMaterno: "López",
    correoElectronico: "maria.gonzalez@colegio.edu.pe",
  },
  {
    id: "3",
    dni: "45678912",
    nombre: "Carlos Alberto",
    apellido1: "Rodríguez",
    apellido2: "Martínez",
    telefono: "965432109",
    email: "carlos.rodriguez@colegio.edu.pe",
    direccion: "Calle Conocimiento 789, Lima",
    nombreDocente: "Carlos Alberto",
    apellidoPaterno: "Rodríguez",
    apellidoMaterno: "Martínez",
    correoElectronico: "carlos.rodriguez@colegio.edu.pe",
  },
  {
    id: "4",
    dni: "78912345",
    nombre: "Ana Sofía",
    apellido1: "Sánchez",
    apellido2: "Fernández",
    telefono: "954321098",
    email: "ana.sanchez@colegio.edu.pe",
    direccion: "Av. Sabiduría 321, Lima",
    nombreDocente: "Ana Sofía",
    apellidoPaterno: "Sánchez",
    apellidoMaterno: "Fernández",
    correoElectronico: "ana.sanchez@colegio.edu.pe",
  },
  {
    id: "5",
    dni: "56789123",
    nombre: "Luis Fernando",
    apellido1: "Torres",
    apellido2: "Ramírez",
    telefono: "943210987",
    email: "luis.torres@colegio.edu.pe",
    direccion: "Jr. Enseñanza 654, Lima",
    nombreDocente: "Luis Fernando",
    apellidoPaterno: "Torres",
    apellidoMaterno: "Ramírez",
    correoElectronico: "luis.torres@colegio.edu.pe",
  },
]
